### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hemanth** [hemanth/issuers#1]
- [ ] Support more languages.
- [ ] Make a `util.js`.
- [ ] Separated out `issueTypes`.
